language: generic
before_install:
- sudo apt-get install texlive-binaries
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- if ! command -v conda > /dev/null; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; bash miniconda.sh -b -p $HOME/miniconda -u; conda config --add
  channels conda-forge; conda config --set always_yes yes; conda install tectonic==0.1.11;
  fi
- conda install -c malramsay biber==2.11 --yes
- conda info -a
cache:
  directories:
  - "$HOME/miniconda"
  - "$HOME/.cache/Tectonic"
script:
- cd ./dissertation_thesis/
- tectonic --keep-intermediates --reruns 0 ./dissertation_thesis.tex
- if [ -f "main.bcf" ]; then biber main; fi
- tectonic ./dissertation_thesis.tex --print
- cd ../
deploy:
  provider: releases
  api_key:
    secure: aS78CFAHReqVIGXH5NdL5PbF3RyXhEFCFrtiwfuaII8QSB7SPsU4lPNNsi6Vsp1RMuDSts/oJyaRERCAdEKo5KxXw01FyjWcEV96hda2WAlR95CEPu/3pPlobqlFVEIrGrZSlkVxSmOFqpeT+qUS05bTLg17daXr4IdE7sI9phZ7KpRM6aBb59lZEDVR0eGRkdJwDjXKCEcak3Zzb+nFoyDRDNuv7F30ZRLo4IyBVbax2ZYRPpMg4TULUWPYI3s5cVJJXOgd+ss8RTE4dQOMKffI0YqE+ZQiAgCTXrN3+nHbnpPvRQQ2sEBwzR+bz4xmY3yaLPe4qcMMt0wC1n9n/0ftboYqsjFtgDxH40tYJ7fPS0g9vmrFJuCYClHoQ2Cr1v7JL8NDSMRy4HyN9/Q69rt25GeyIovyrIeUxxVoLUA5AHJXBYrGqIuQjOWZOPQP9lI4Lzfh6vZxWzSGEAEgZAWF7gwb8sS4EO6Vuz3wFQQcgn/kzG6971CeVnJzF7V4UAhiSr42o0G9oVsNkVdVtwcMmssM0ClvNV75p/1hDJTWRlFTD9nkT/09SMsUuGenbFO/NOdNxfA9XSmqcKBTG+nswKSNgf6UYx0RiYZ0L59kEZfcFNhoj9WoCJsvcKutofiS/lKti83PL7so0NJ05Y7h7rGfk5HyAblVxGjw0VA=
  file: ./dissertation_thesis/dissertation_thesis.pdf
  on:
    repo: QDucasse/dissertation_thesis
    tags: 'true'
  skip_cleanup: 'true'
notifications:
  email: 'false'
